### ISSUE TITLE
Welcome Users

### ISSUE THREAD

**Issue by XHiddenProjects** [surveybuilderteams/surveybuilder#1]
Hi everyone, this is @surveybuilder-admin here hope you enjoy the build. Please make sure you you download it and have it on your website. 

# Here are some info’s

- [X] Form Elements
- [X] Config file
- [X] Import, Export and Editable console.
- [X] Custom Plug-in(s) HTML code supported only
- [X] In-Form apps
- [X] CPanel
- [X] Custom CSS/Js and add-on's
- [X] mySQL database Support
- [X] In-App configuration
- [X] Editors Tools
- [ ] In-app publish
- [ ] SQLite database support 
- [ ] Self Grading Form
- [x] Limit Title characters

# Website

Here is our website [SurveyBuilder](http://surveybuilder.epizy.com/Home.php/ "SurveyBuilder-Website")

**Comment by Amoldreamer** [comment]
Hi there,
  I got an invitation from the surveybuilder team. As I am a new developer trying to make some open source contributions I am unable to understand what it's all about. What I could understand from the brief description is that it's some kind of form builder. Can you please give me some more details about it?

**Comment by XHiddenProjects** [comment]
Yes it is a web form builder, with high quality coding system, if you do not know how to code I can share some codes that you can copy and paste. This is also a configurable survey form. The codes I am mostly using in PHP and HTML. I am currently working on a animations in-general.

# What can be used

* You can use custom CSS and JavaScript to create your own  way of pathway(ex. Conditions ) 
* You can also link up your own CSS/JavaScript from your website(make sure it doesn't override it)
* and more.

# Dependencies 
* mySQL Server is required(if want to store Database)
* API.txt file to make the file run: you can get API here  [API](http://surveybuilder.epizy.com/API/GetAPI.php)
* Will need a Localhost server or attachment to your website to run::ex [Xampp](https://www.apachefriends.org/download.html)

# What do you need to know
* Basic web designing codes  (that basically all of it)

# Here is what it looks like

<img src="https://github.com/surveybuilderteams/surveybuilder/blob/master/banner/img/SurveyBuilder-Image.png?raw=true" alt="SurveyBuilder-Image" title="SurveyBuilder">

# Recent Updates
* Created Themes
* Drawing(Using SVG)
* and more...

# Any Questions 

Please feel free to comment your question. I won't be able to respond right away, but I will try to get back to your question soon as possible: You can preview the work [here](http://surveybuilder.epizy.com/Home)
